# Site settings
title: Ryan Conk's Portfolio
description: Ryan Conk's Yoga Teacher Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ryan Conk
user_description: Passionate yoga enthusiast with a transformative personal journey sparked by healing and self-discovery. Found solace and growth through yoga during challenging times. Dedicated to fostering inclusive spaces for others to explore physical, mental, and spiritual well-being. Committed to promoting mental health awareness and advocating for yoga as a healthy coping mechanism. Passionate about normalizing men's mental health practices through yoga, movement, and self-care. Aspiring yoga teacher focused on guiding individuals towards inner harmony and holistic wellness, both on and off the mat.

certificate: 200 Hr Yoga Alliance Certified Teacher
user_title: 200 Hr Certified Yoga Teacher
email: ryangconk@gmail.com
twitter_username:
github_username: RyanGC93
gplus_username:

# Google-analytics
google-analytics:
  id: ""

exclude: ["package.json", "src", "node_modules"]
